name: tests

on: [push, pull_request]

env:
  all_os: [ubuntu-latest, macos-latest]

jobs:
  flake8:
    strategy:
      matrix:
        os: all_os
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install dependencies
      run: python -m pip install --upgrade pip tox
    - name: run flake8
      run: tox -e flake8

  mypy:
    strategy:
      matrix:
        os: all_os
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install dependencies
      run: python -m pip install --upgrade pip tox
    - name: run mypy
      run: tox -e mypy

  pylint:
    strategy:
      matrix:
        os: all_os
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2s
      with:
        python-version: 3.8
    - name: install dependencies
      run: python -m pip install --upgrade pip tox
    - name: run pylint
      run: tox -e pylint

  black:
    strategy:
      matrix:
        os: all_os
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install dependencies
      run: python -m pip install --upgrade pip tox
    - name: run black
      run: tox -e black

  tilescope:
    strategy:
      matrix:
        os: all_os
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install dependencies
      run: python -m pip install --upgrade pip tox
    - name: run tilescope
      run: tox -e tilescope

  py36:
    strategy:
      matrix:
        os: all_os

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: install dependencies
      run: python -m pip install --upgrade pip tox
    - name: run pytest py36
      run: tox -e py36

  py37:
    strategy:
      matrix:
        os: all_os

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: install dependencies
      run: python -m pip install --upgrade pip tox
    - name: run pytest py37
      run: tox -e py37

  py38:
    strategy:
      matrix:
        os: all_os

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: install dependencies
      run: python -m pip install --upgrade pip tox
    - name: run pytest py38
      run: tox -e py38

  py39:
    strategy:
      matrix:
        os: all_os

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9-dev
    - name: install dependencies
      run: python -m pip install --upgrade pip tox virtualenv
    - name: run pytest py39
      run: tox -e py39

  pypy36:
    strategy:
      matrix:
        os: all_os

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: pypy3
    - name: install dependencies
      run: python -m pip install --upgrade pip tox
    - name: run pytest pypy3
      run: tox -e pypy36
